sudo: required
dist: xenial

stages:
  - test
  - deploy

cache:
  directories:
    - $HOME/haxe

language: node_js
node_js: 10

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=stable
  - HAXE_VERSION=latest
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  # Use a stable container (node) to test the clients in all targets
  - haxe master.hxml -D containers=node -D targets=js,node,php,neko,cpp #,cs
  - if [[ "$(haxe -version)" =~ ^4.* ]]; then haxe master.hxml -D containers=node -D targets=hl,python,lua; fi
  # Use a stable client (node) to test the containers
  - haxe master.hxml -D containers=node-tcp,neko-mod -D targets=node -D container_only
  
  # - haxe master.hxml -D containers=php -D targets=node -D container_only # Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version.
  # - haxe master.hxml -D containers=neko-tools -D targets=node # does not support PATCH/PUT/DELETE
  # - haxe master.hxml -D containers=node -D targets=cpp # haxeshim not working with cpp yet
  # - haxe master.hxml -D containers=tcp -D targets=node -lib tink_tcp -lib tink_runloop

jobs:
  include:
    # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
    - stage: deploy
      os: linux
      install:
        - npm i -g lix
        - lix download
      script: skip
      env:
        secure: PKQDLOwF+mIUQWVabqSXJffivKfWT1rjRVXw+yx97wlBzoK7n9KV4YRlh0elLGEB7oGJevpnS2s9zZ7cF/ruR7fAL271sqUY5oM7hFFzcPtgw9FUxyOHHeChrrlx8qkn51CQtNZnAULCQ2b5obICxCkRph+Ek5/o6HxYdppF9r4=
      after_success:
        - lix run travix install
        - lix run travix release
